### PR TITLE
Added id param in Calendar::event method

### PR DESCRIPTION
**Pull request by nezaboravi**
Added $id param in Calendar::event

### CODE REVIEW

**Comment by maddhatter** [comment]
Could you update this so that the `$id` parameter has a default value of `null`, so it becomes optional?

Thx

**Comment by nezaboravi** [comment]
Sure, dont know how i missed it at first time. Updated.

**Comment by nezaboravi** [comment]
@maddhatter  is it possible to accept this  i need on my project :) Thanks :)

**Comment by maddhatter** [comment]
Just tagged v1.2.2 with this

**Pull request merged**
