### PR TITLE
Adding new way of configuring the calendar.

### PR DESCRIPTION
**Pull request by melanholly**
The old way of configuring the Calendar widget was not customizable. Now we can set all the different options of fullcalendar:  http://fullcalendar.io/docs/  adding a default language and stuff.

### CODE REVIEW

**Comment by maddhatter** [comment]
Can you see if [v0.2.0](https://github.com/maddhatter/laravel-fullcalendar/releases/tag/v0.2.0) does what you need? (or [v1.1.0](https://github.com/maddhatter/laravel-fullcalendar/releases/tag/v1.1.0) for Laravel 5)

**Comment by melanholly** [comment]
Yes it does but you can't specify the select callback. I will write new pull request on monday for that reason.

**Comment by maddhatter** [comment]
I see what you mean...

Try the latest version? ([v0.2.1](https://github.com/maddhatter/laravel-fullcalendar/releases/tag/v0.2.1) or [v1.1.1](https://github.com/maddhatter/laravel-fullcalendar/releases/tag/v1.1.1))

**Comment by melanholly** [comment]
The latest version is actually doing the things as they should be. Thank you.

**Pull request closed without merging**
